name: Java CI with Maven - Test and package
on: [pull_request] # Ce workflow se déclenche sur un pull_request dans le dépôt
jobs:
  Pull_Request: # Nom du job
    name: Pull_Request
    runs-on: ubuntu-latest # OS où s'exécute le job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
      - run: mvn -B package