name : Java CI with Maven - Test and package

on :
  pull_request :
    branch :
      - main

jobs :
  build :
    runs-on : ubuntu-latest

    steps :
      - name : Checkout
        uses : actions/checkout@v4

      - name : Setup (java21)
        uses : actions/setup-java@v4
        with :
          java-version : '21'
          distribution : 'correto'

      - name : Build (maven)
        run : mvn -B package