name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: se placer dans le depot courant
        uses: actions/checkout@v4

      - name: Choisir java 21 et corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: construction package maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}