name: Java CI with Maven - Test and package
on: [pull_request] # Ce workflow se déclenche sur un pull_request dans le dépôt
jobs:
  Pull_Request: # Nom du job
    runs-on: ubuntu-latest # OS où s'exécute le job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Build Maven
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')